//! `enoxian://` invite URI encoding, decoding, and expiry validation.
//!
//! Binary payload (variable length, base64url-no-pad, no query string):
//!   bytes  0-15   circle UUID (big-endian)
//!   bytes 16-47   PSK (32 raw bytes)
//!   bytes 48-55   expires_at as i64 Unix timestamp (big-endian)
//!   byte  56      name length N (u8)
//!   bytes 57..    circle_name (UTF-8, N bytes)
//!   byte  57+N    peer length M (u8)
//!   bytes 58+N..  peer_addr (UTF-8, M bytes)
//!
//! Full URI (no query string — safe to paste in any shell without quoting):
//!   enoxian://v1/<base64url-no-pad>

use anyhow::{bail, Context, Result};
use base64::{engine::general_purpose::URL_SAFE_NO_PAD, Engine};
use chrono::{DateTime, Duration, Utc};
use uuid::Uuid;

const SCHEME_PREFIX: &str = "enoxian://v1/";
const MIN_LEN: usize = 58; // 16 + 32 + 8 + 1 + 1

pub struct InvitePayload {
    pub circle_id: String,
    pub psk_bytes: [u8; 32],
    pub circle_name: Option<String>,
    pub expires_at: DateTime<Utc>,
    pub peer_addr: Option<String>,
    /// Admin public key (protobuf-encoded bytes). Present when generated by the circle admin.
    pub admin_pubkey_bytes: Option<Vec<u8>>,
    /// Circuit relay multiaddr (e.g. /ip4/1.2.3.4/tcp/36521/p2p/<peer_id>).
    /// Joinees add this to their relay_addrs and use it for WAN connectivity.
    pub relay_addr: Option<String>,
    /// Rendezvous server multiaddr (QUIC, e.g. /ip4/1.2.3.4/udp/36521/quic-v1/p2p/<peer_id>).
    /// Joinees add this to their rendezvous_addrs for automatic peer discovery.
    pub rendezvous_addr: Option<String>,
    /// The grant: who issued this invite, a one-time nonce, and their signature.
    ///
    /// Present on invites minted by a member; absent on invites predating the
    /// grant. Without it an invite is only a bearer credential — anyone holding
    /// the circle's PSK can mint one, set any expiry they like, and no later
    /// change to the circle can invalidate it. The grant binds the invite to a
    /// member whose standing is re-checked when it is redeemed.
    pub grant: Option<InviteGrant>,
}

/// Issuer, nonce and signature carried by an invite.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct InviteGrant {
    /// hex(protobuf) of the issuing member's per-circle public key.
    ///
    /// The key rather than the peer ID: the peer ID is derived from it, so this
    /// both identifies the issuer and verifies the signature without a lookup.
    pub inviter_pubkey_hex: String,
    /// One-time identifier, recorded when redeemed so an invite admits once.
    pub nonce: String,
    /// hex(sign(inviter_circle_key, [`grant_message`]))
    pub sig: String,
}

impl InviteGrant {
    /// Peer ID of the issuer, derived from the carried key.
    pub fn inviter_peer_id(&self) -> Result<String> {
        Ok(self.inviter_public_key()?.to_peer_id().to_string())
    }

    fn inviter_public_key(&self) -> Result<libp2p::identity::PublicKey> {
        let bytes = hex::decode(self.inviter_pubkey_hex.trim())
            .context("inviter public key is not valid hex")?;
        libp2p::identity::PublicKey::try_decode_protobuf(&bytes)
            .map_err(|e| anyhow::anyhow!("invalid inviter public key: {e}"))
    }
}

/// Mint a grant for an invite, signing with this member's per-circle key.
///
/// Every member holds such a key, so issuing invites stays open to the whole
/// circle — the grant records *which* member issued it, not that an admin did.
pub fn sign_grant(
    circle_id: &str,
    keypair_proto_hex: &str,
    expires_at: DateTime<Utc>,
) -> Result<InviteGrant> {
    let keypair = crate::crypto::keypair_from_hex(keypair_proto_hex)?;
    let nonce = Uuid::new_v4().to_string();
    let sig = keypair
        .sign(&grant_message(circle_id, &nonce, expires_at))
        .map_err(|e| anyhow::anyhow!("signing invite grant failed: {e}"))?;
    Ok(InviteGrant {
        inviter_pubkey_hex: hex::encode(keypair.public().encode_protobuf()),
        nonce,
        sig: hex::encode(sig),
    })
}

/// Check that a grant was signed by the key it names, over this circle, nonce
/// and expiry.
///
/// This proves only authorship. Whether the issuer is *still* entitled to admit
/// anyone is a separate question, answered against live membership at the point
/// the invite is redeemed — that separation is what lets removing a member
/// invalidate the invites they issued.
pub fn verify_grant(circle_id: &str, grant: &InviteGrant, expires_at: DateTime<Utc>) -> Result<()> {
    let pubkey = grant.inviter_public_key()?;
    let sig = hex::decode(grant.sig.trim()).context("grant signature is not valid hex")?;
    if !pubkey.verify(&grant_message(circle_id, &grant.nonce, expires_at), &sig) {
        bail!("invite grant signature does not match the issuing key");
    }
    Ok(())
}

/// Canonical bytes an inviter signs. Covers the circle, the nonce and the
/// expiry, so none of the three can be altered without invalidating the grant —
/// which is what makes a TTL mean anything.
pub fn grant_message(circle_id: &str, nonce: &str, expires_at: DateTime<Utc>) -> Vec<u8> {
    format!("invite:{circle_id}:{nonce}:{}", expires_at.timestamp()).into_bytes()
}

// ── Encoding ──────────────────────────────────────────────────────────────────

pub fn encode(payload: &InvitePayload) -> String {
    let uuid = Uuid::parse_str(&payload.circle_id).expect("circle_id must be a valid UUID");

    let name_bytes = payload.circle_name.as_deref().unwrap_or("").as_bytes();
    let peer_bytes = payload.peer_addr.as_deref().unwrap_or("").as_bytes();
    assert!(name_bytes.len() <= 255, "circle name too long");
    assert!(peer_bytes.len() <= 255, "peer addr too long");

    let admin_bytes = payload.admin_pubkey_bytes.as_deref().unwrap_or(&[]);
    let relay_bytes = payload.relay_addr.as_deref().unwrap_or("").as_bytes();
    let rendezvous_bytes = payload.rendezvous_addr.as_deref().unwrap_or("").as_bytes();
    assert!(admin_bytes.len() <= 65535, "admin pubkey too long");
    assert!(relay_bytes.len() <= 65535, "relay addr too long");
    assert!(rendezvous_bytes.len() <= 65535, "rendezvous addr too long");

    let mut raw = Vec::with_capacity(
        MIN_LEN
            + name_bytes.len()
            + peer_bytes.len()
            + 2
            + admin_bytes.len()
            + 2
            + relay_bytes.len()
            + 2
            + rendezvous_bytes.len(),
    );
    raw.extend_from_slice(uuid.as_bytes()); // 0-15
    raw.extend_from_slice(&payload.psk_bytes); // 16-47
    raw.extend_from_slice(&payload.expires_at.timestamp().to_be_bytes()); // 48-55
    raw.push(name_bytes.len() as u8); // 56
    raw.extend_from_slice(name_bytes); // 57..57+N
    raw.push(peer_bytes.len() as u8); // 57+N
    raw.extend_from_slice(peer_bytes); // 58+N..
                                       // Extension 1: admin pubkey (u16 BE length + bytes); absent in old invites
    let admin_len = admin_bytes.len() as u16;
    raw.extend_from_slice(&admin_len.to_be_bytes());
    raw.extend_from_slice(admin_bytes);
    // Extension 2: relay addr (u16 BE length + bytes); absent in old invites
    let relay_len = relay_bytes.len() as u16;
    raw.extend_from_slice(&relay_len.to_be_bytes());
    raw.extend_from_slice(relay_bytes);
    // Extension 3: rendezvous addr (u16 BE length + bytes); absent in old invites
    let rendezvous_len = rendezvous_bytes.len() as u16;
    raw.extend_from_slice(&rendezvous_len.to_be_bytes());
    raw.extend_from_slice(rendezvous_bytes);

    // Extension 4: the grant — inviter peer id, nonce, signature. Each is a
    // u16 BE length prefix followed by bytes. Absent on invites minted before
    // grants existed, which decode with `grant: None`.
    let (inviter, nonce, sig) = match &payload.grant {
        Some(g) => (
            g.inviter_pubkey_hex.as_str(),
            g.nonce.as_str(),
            g.sig.as_str(),
        ),
        None => ("", "", ""),
    };
    for field in [inviter, nonce, sig] {
        let bytes = field.as_bytes();
        assert!(bytes.len() <= 65535, "grant field too long");
        raw.extend_from_slice(&(bytes.len() as u16).to_be_bytes());
        raw.extend_from_slice(bytes);
    }

    format!("{SCHEME_PREFIX}{}", URL_SAFE_NO_PAD.encode(&raw))
}

// ── Decoding ──────────────────────────────────────────────────────────────────

pub fn decode(uri: &str) -> Result<InvitePayload> {
    // Strip any query string that old clients might have produced
    let uri_clean = uri.split_once('?').map(|(base, _)| base).unwrap_or(uri);

    let b64 = uri_clean
        .strip_prefix(SCHEME_PREFIX)
        .with_context(|| format!("not a valid enoxian:// URI: {uri}"))?;

    let raw = URL_SAFE_NO_PAD
        .decode(b64)
        .context("invite URI payload is not valid base64url")?;

    if raw.len() < MIN_LEN {
        bail!(
            "invite payload is {} bytes, expected at least {MIN_LEN}",
            raw.len()
        );
    }

    let uuid_bytes: [u8; 16] = raw[..16].try_into().unwrap();
    let circle_id = Uuid::from_bytes(uuid_bytes).to_string();

    let psk_bytes: [u8; 32] = raw[16..48].try_into().unwrap();

    let ts = i64::from_be_bytes(raw[48..56].try_into().unwrap());
    let expires_at = DateTime::from_timestamp(ts, 0).context("invalid timestamp in invite")?;

    let name_len = raw[56] as usize;
    if 57 + name_len >= raw.len() {
        bail!("invite payload truncated at name field");
    }
    let circle_name = if name_len == 0 {
        None
    } else {
        Some(
            String::from_utf8(raw[57..57 + name_len].to_vec())
                .context("circle name is not valid UTF-8")?,
        )
    };

    let peer_offset = 57 + name_len;
    let peer_len = raw[peer_offset] as usize;
    let peer_addr = if peer_len == 0 {
        None
    } else {
        let start = peer_offset + 1;
        let end = start + peer_len;
        if end > raw.len() {
            bail!("invite payload truncated at peer field");
        }
        Some(String::from_utf8(raw[start..end].to_vec()).context("peer addr is not valid UTF-8")?)
    };

    // Extension 1: admin pubkey (u16 BE length prefix). Absent in older invites.
    let ext1_offset = peer_offset + 1 + peer_len;
    let (admin_pubkey_bytes, ext2_offset) = if ext1_offset + 2 <= raw.len() {
        let len = u16::from_be_bytes([raw[ext1_offset], raw[ext1_offset + 1]]) as usize;
        let start = ext1_offset + 2;
        let end = start + len;
        if len > 0 && end <= raw.len() {
            (Some(raw[start..end].to_vec()), end)
        } else {
            (None, start)
        }
    } else {
        (None, ext1_offset)
    };

    // Extension 2: relay addr (u16 BE length prefix). Absent in older invites.
    let (relay_addr, ext3_offset) = if ext2_offset + 2 <= raw.len() {
        let len = u16::from_be_bytes([raw[ext2_offset], raw[ext2_offset + 1]]) as usize;
        let start = ext2_offset + 2;
        let end = start + len;
        if len > 0 && end <= raw.len() {
            (
                Some(
                    String::from_utf8(raw[start..end].to_vec())
                        .context("relay addr is not valid UTF-8")?,
                ),
                end,
            )
        } else {
            (None, start)
        }
    } else {
        (None, ext2_offset)
    };

    // Extension 3: rendezvous addr (u16 BE length prefix). Absent in older invites.
    let mut ext4_offset = ext3_offset;
    let rendezvous_addr = if ext3_offset + 2 <= raw.len() {
        let len = u16::from_be_bytes([raw[ext3_offset], raw[ext3_offset + 1]]) as usize;
        let start = ext3_offset + 2;
        let end = start + len;
        if len > 0 && end <= raw.len() {
            ext4_offset = end;
            Some(
                String::from_utf8(raw[start..end].to_vec())
                    .context("rendezvous addr is not valid UTF-8")?,
            )
        } else {
            ext4_offset = start;
            None
        }
    } else {
        None
    };

    // Extension 4: the grant. All three fields must be present and non-empty
    // for the invite to carry one; anything else decodes as no grant at all,
    // never as a partial one that might be waved through downstream.
    let mut grant_fields: Vec<String> = Vec::with_capacity(3);
    let mut offset = ext4_offset;
    for _ in 0..3 {
        if offset + 2 > raw.len() {
            break;
        }
        let len = u16::from_be_bytes([raw[offset], raw[offset + 1]]) as usize;
        let start = offset + 2;
        let end = start + len;
        if end > raw.len() {
            break;
        }
        grant_fields.push(
            String::from_utf8(raw[start..end].to_vec())
                .context("grant field is not valid UTF-8")?,
        );
        offset = end;
    }
    let grant = match grant_fields.as_slice() {
        [inviter, nonce, sig] if !inviter.is_empty() && !nonce.is_empty() && !sig.is_empty() => {
            Some(InviteGrant {
                inviter_pubkey_hex: inviter.clone(),
                nonce: nonce.clone(),
                sig: sig.clone(),
            })
        }
        _ => None,
    };

    Ok(InvitePayload {
        circle_id,
        psk_bytes,
        circle_name,
        expires_at,
        peer_addr,
        admin_pubkey_bytes,
        relay_addr,
        rendezvous_addr,
        grant,
    })
}

// ── Expiry ────────────────────────────────────────────────────────────────────

pub fn check_expiry(payload: &InvitePayload) -> Result<()> {
    let now = Utc::now();
    if now > payload.expires_at {
        let ago = now - payload.expires_at;
        bail!(
            "invite expired {} ago (at {})",
            format_duration(ago),
            payload.expires_at.format("%Y-%m-%d %H:%M UTC")
        );
    }
    Ok(())
}

// ── TTL parsing ───────────────────────────────────────────────────────────────

pub fn parse_ttl(s: &str) -> Result<Duration> {
    if let Some(days) = s.strip_suffix('d') {
        let n: i64 = days.parse().context("invalid number of days in TTL")?;
        Ok(Duration::days(n))
    } else if let Some(hours) = s.strip_suffix('h') {
        let n: i64 = hours.parse().context("invalid number of hours in TTL")?;
        Ok(Duration::hours(n))
    } else {
        bail!("invalid TTL '{s}' — use e.g. '7d' or '24h'")
    }
}

// ── Helpers ───────────────────────────────────────────────────────────────────

fn format_duration(d: Duration) -> String {
    let secs = d.num_seconds().abs();
    if secs < 60 {
        format!("{secs}s")
    } else if secs < 3600 {
        format!("{}m", secs / 60)
    } else if secs < 86400 {
        format!("{}h", secs / 3600)
    } else {
        format!("{}d", secs / 86400)
    }
}

// ── Tests ─────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn round_trip_basic() {
        let psk = [42u8; 32];
        let expires = Utc::now() + Duration::days(7);
        let payload = InvitePayload {
            grant: None,
            circle_id: "8e563c41-f0ec-4225-9764-064f1fb04341".to_string(),
            psk_bytes: psk,
            circle_name: Some("TestCircle".to_string()),
            expires_at: expires,
            peer_addr: Some("/ip4/1.2.3.4/tcp/9091".to_string()),
            admin_pubkey_bytes: None,
            relay_addr: Some("/ip4/5.6.7.8/tcp/36521/p2p/12D3KooWtest".to_string()),
            rendezvous_addr: Some("/ip4/9.10.11.12/udp/36521/quic-v1/p2p/12D3KooWrdvz".to_string()),
        };

        let uri = encode(&payload);
        assert!(uri.starts_with("enoxian://v1/"));
        assert!(!uri.contains('?'), "URI must not have a query string");
        assert!(!uri.contains('&'), "URI must not contain & (shell unsafe)");

        let decoded = decode(&uri).unwrap();
        assert_eq!(decoded.circle_id, payload.circle_id);
        assert_eq!(decoded.psk_bytes, psk);
        assert_eq!(decoded.circle_name.as_deref(), Some("TestCircle"));
        assert_eq!(decoded.peer_addr.as_deref(), Some("/ip4/1.2.3.4/tcp/9091"));
        assert_eq!(
            decoded.relay_addr.as_deref(),
            Some("/ip4/5.6.7.8/tcp/36521/p2p/12D3KooWtest")
        );
        assert_eq!(
            decoded.rendezvous_addr.as_deref(),
            Some("/ip4/9.10.11.12/udp/36521/quic-v1/p2p/12D3KooWrdvz")
        );
        // expires_at loses sub-second precision (stored as i64 unix seconds)
        assert_eq!(decoded.expires_at.timestamp(), expires.timestamp());
    }

    #[test]
    fn round_trip_no_name_no_peer() {
        let psk = [0u8; 32];
        let expires = Utc::now() + Duration::hours(24);
        let payload = InvitePayload {
            grant: None,
            circle_id: "8e563c41-f0ec-4225-9764-064f1fb04341".to_string(),
            psk_bytes: psk,
            circle_name: None,
            expires_at: expires,
            peer_addr: None,
            admin_pubkey_bytes: None,
            relay_addr: None,
            rendezvous_addr: None,
        };
        let uri = encode(&payload);
        let decoded = decode(&uri).unwrap();
        assert!(decoded.circle_name.is_none());
        assert!(decoded.peer_addr.is_none());
    }

    #[test]
    fn expiry_detected() {
        let psk = [0u8; 32];
        let payload = InvitePayload {
            grant: None,
            circle_id: "8e563c41-f0ec-4225-9764-064f1fb04341".to_string(),
            psk_bytes: psk,
            circle_name: None,
            expires_at: Utc::now() - Duration::hours(1),
            peer_addr: None,
            admin_pubkey_bytes: None,
            relay_addr: None,
            rendezvous_addr: None,
        };
        let uri = encode(&payload);
        let decoded = decode(&uri).unwrap();
        assert!(check_expiry(&decoded).is_err());
    }

    #[test]
    fn ttl_parsing() {
        assert_eq!(parse_ttl("7d").unwrap(), Duration::days(7));
        assert_eq!(parse_ttl("24h").unwrap(), Duration::hours(24));
        assert!(parse_ttl("bad").is_err());
    }
}

#[cfg(test)]
mod grant_tests {
    use super::*;
    use crate::crypto::keypair_to_hex;
    use libp2p::identity::Keypair;

    fn member() -> (String, String) {
        let kp = Keypair::generate_ed25519();
        (
            keypair_to_hex(&kp).unwrap(),
            kp.public().to_peer_id().to_string(),
        )
    }

    #[test]
    fn a_grant_verifies_and_names_its_issuer() {
        let (hex, peer) = member();
        let exp = Utc::now() + Duration::days(1);
        let grant = sign_grant("circle-1", &hex, exp).unwrap();
        assert!(verify_grant("circle-1", &grant, exp).is_ok());
        assert_eq!(grant.inviter_peer_id().unwrap(), peer);
    }

    /// The signature covers circle, nonce and expiry, so none can be edited
    /// after the fact. Extending the expiry is the interesting one: without it
    /// covered, a TTL would be a suggestion rather than a limit.
    #[test]
    fn none_of_the_signed_fields_can_be_altered() {
        let (hex, _) = member();
        let exp = Utc::now() + Duration::days(1);
        let grant = sign_grant("circle-1", &hex, exp).unwrap();

        assert!(verify_grant("circle-2", &grant, exp).is_err(), "circle");
        assert!(
            verify_grant("circle-1", &grant, exp + Duration::days(365)).is_err(),
            "expiry"
        );
        let mut tampered = grant.clone();
        tampered.nonce = "different".into();
        assert!(verify_grant("circle-1", &tampered, exp).is_err(), "nonce");
    }

    /// A grant cannot be re-attributed to someone else: swapping in another
    /// member's key breaks the signature, so an invite can never appear to
    /// have been issued by a member who did not issue it.
    #[test]
    fn a_grant_cannot_be_reattributed_to_another_member() {
        let (issuer_hex, _) = member();
        let (_, other_peer) = member();
        let (other_hex, _) = member();
        let exp = Utc::now() + Duration::days(1);

        let mut grant = sign_grant("circle-1", &issuer_hex, exp).unwrap();
        let other_pub = crate::crypto::keypair_from_hex(&other_hex)
            .unwrap()
            .public()
            .encode_protobuf();
        grant.inviter_pubkey_hex = hex::encode(other_pub);

        assert!(verify_grant("circle-1", &grant, exp).is_err());
        assert_ne!(grant.inviter_peer_id().unwrap(), other_peer);
    }

    #[test]
    fn a_grant_survives_the_invite_encoding() {
        let (hex, peer) = member();
        let exp = Utc::now() + Duration::days(1);
        let grant = sign_grant("00000000-0000-0000-0000-000000000001", &hex, exp).unwrap();
        let uri = encode(&InvitePayload {
            circle_id: "00000000-0000-0000-0000-000000000001".into(),
            psk_bytes: [7u8; 32],
            circle_name: Some("c".into()),
            expires_at: exp,
            peer_addr: None,
            admin_pubkey_bytes: None,
            relay_addr: None,
            rendezvous_addr: None,
            grant: Some(grant),
        });
        let back = decode(&uri)
            .unwrap()
            .grant
            .expect("grant survives encoding");
        assert_eq!(back.inviter_peer_id().unwrap(), peer);
        assert!(verify_grant("00000000-0000-0000-0000-000000000001", &back, exp).is_ok());
    }

    /// Invites minted before grants existed must still decode — as carrying no
    /// grant, never as a partial one that downstream might treat as present.
    #[test]
    fn an_invite_without_a_grant_decodes_as_none() {
        let uri = encode(&InvitePayload {
            circle_id: "00000000-0000-0000-0000-000000000002".into(),
            psk_bytes: [1u8; 32],
            circle_name: None,
            expires_at: Utc::now() + Duration::days(1),
            peer_addr: None,
            admin_pubkey_bytes: None,
            relay_addr: None,
            rendezvous_addr: None,
            grant: None,
        });
        assert!(decode(&uri).unwrap().grant.is_none());
    }
}
