//! `enoxian://` invite URI encoding, decoding, and expiry validation.
//!
//! Binary payload (variable length, base64url-no-pad, no query string):
//!   bytes  0-15   circle UUID (big-endian)
//!   bytes 16-47   PSK (32 raw bytes)
//!   bytes 48-55   expires_at as i64 Unix timestamp (big-endian)
//!   byte  56      name length N (u8)
//!   bytes 57..    circle_name (UTF-8, N bytes)
//!   byte  57+N    peer length M (u8)
//!   bytes 58+N..  peer_addr (UTF-8, M bytes)
//!
//! Full URI (no query string — safe to paste in any shell without quoting):
//!   enoxian://v1/<base64url-no-pad>

use anyhow::{bail, Context, Result};
use base64::{engine::general_purpose::URL_SAFE_NO_PAD, Engine};
use chrono::{DateTime, Duration, Utc};
use uuid::Uuid;

const SCHEME_PREFIX: &str = "enoxian://v1/";
const MIN_LEN: usize = 58; // 16 + 32 + 8 + 1 + 1

pub struct InvitePayload {
    pub circle_id:        String,
    pub psk_bytes:        [u8; 32],
    pub circle_name:      Option<String>,
    pub expires_at:       DateTime<Utc>,
    pub peer_addr:        Option<String>,
    /// Admin public key (protobuf-encoded bytes). Present when generated by the circle admin.
    pub admin_pubkey_bytes: Option<Vec<u8>>,
    /// Circuit relay multiaddr (e.g. /ip4/1.2.3.4/tcp/36521/p2p/<peer_id>).
    /// Joinees add this to their relay_addrs and use it for WAN connectivity.
    pub relay_addr: Option<String>,
    /// Rendezvous server multiaddr (QUIC, e.g. /ip4/1.2.3.4/udp/36521/quic-v1/p2p/<peer_id>).
    /// Joinees add this to their rendezvous_addrs for automatic peer discovery.
    pub rendezvous_addr: Option<String>,
}

// ── Encoding ──────────────────────────────────────────────────────────────────

pub fn encode(payload: &InvitePayload) -> String {
    let uuid = Uuid::parse_str(&payload.circle_id).expect("circle_id must be a valid UUID");

    let name_bytes = payload.circle_name.as_deref().unwrap_or("").as_bytes();
    let peer_bytes = payload.peer_addr.as_deref().unwrap_or("").as_bytes();
    assert!(name_bytes.len() <= 255, "circle name too long");
    assert!(peer_bytes.len() <= 255, "peer addr too long");

    let admin_bytes = payload.admin_pubkey_bytes.as_deref().unwrap_or(&[]);
    let relay_bytes = payload.relay_addr.as_deref().unwrap_or("").as_bytes();
    let rendezvous_bytes = payload.rendezvous_addr.as_deref().unwrap_or("").as_bytes();
    assert!(admin_bytes.len() <= 65535, "admin pubkey too long");
    assert!(relay_bytes.len() <= 65535, "relay addr too long");
    assert!(rendezvous_bytes.len() <= 65535, "rendezvous addr too long");

    let mut raw = Vec::with_capacity(
        MIN_LEN + name_bytes.len() + peer_bytes.len()
            + 2 + admin_bytes.len() + 2 + relay_bytes.len() + 2 + rendezvous_bytes.len()
    );
    raw.extend_from_slice(uuid.as_bytes());               // 0-15
    raw.extend_from_slice(&payload.psk_bytes);            // 16-47
    raw.extend_from_slice(&payload.expires_at.timestamp().to_be_bytes()); // 48-55
    raw.push(name_bytes.len() as u8);                    // 56
    raw.extend_from_slice(name_bytes);                   // 57..57+N
    raw.push(peer_bytes.len() as u8);                    // 57+N
    raw.extend_from_slice(peer_bytes);                   // 58+N..
    // Extension 1: admin pubkey (u16 BE length + bytes); absent in old invites
    let admin_len = admin_bytes.len() as u16;
    raw.extend_from_slice(&admin_len.to_be_bytes());
    raw.extend_from_slice(admin_bytes);
    // Extension 2: relay addr (u16 BE length + bytes); absent in old invites
    let relay_len = relay_bytes.len() as u16;
    raw.extend_from_slice(&relay_len.to_be_bytes());
    raw.extend_from_slice(relay_bytes);
    // Extension 3: rendezvous addr (u16 BE length + bytes); absent in old invites
    let rendezvous_len = rendezvous_bytes.len() as u16;
    raw.extend_from_slice(&rendezvous_len.to_be_bytes());
    raw.extend_from_slice(rendezvous_bytes);

    format!("{SCHEME_PREFIX}{}", URL_SAFE_NO_PAD.encode(&raw))
}

// ── Decoding ──────────────────────────────────────────────────────────────────

pub fn decode(uri: &str) -> Result<InvitePayload> {
    // Strip any query string that old clients might have produced
    let uri_clean = uri.split_once('?').map(|(base, _)| base).unwrap_or(uri);

    let b64 = uri_clean
        .strip_prefix(SCHEME_PREFIX)
        .with_context(|| format!("not a valid enoxian:// URI: {uri}"))?;

    let raw = URL_SAFE_NO_PAD
        .decode(b64)
        .context("invite URI payload is not valid base64url")?;

    if raw.len() < MIN_LEN {
        bail!("invite payload is {} bytes, expected at least {MIN_LEN}", raw.len());
    }

    let uuid_bytes: [u8; 16] = raw[..16].try_into().unwrap();
    let circle_id = Uuid::from_bytes(uuid_bytes).to_string();

    let psk_bytes: [u8; 32] = raw[16..48].try_into().unwrap();

    let ts = i64::from_be_bytes(raw[48..56].try_into().unwrap());
    let expires_at = DateTime::from_timestamp(ts, 0)
        .context("invalid timestamp in invite")?;

    let name_len = raw[56] as usize;
    if 57 + name_len >= raw.len() {
        bail!("invite payload truncated at name field");
    }
    let circle_name = if name_len == 0 {
        None
    } else {
        Some(String::from_utf8(raw[57..57 + name_len].to_vec())
            .context("circle name is not valid UTF-8")?)
    };

    let peer_offset = 57 + name_len;
    let peer_len = raw[peer_offset] as usize;
    let peer_addr = if peer_len == 0 {
        None
    } else {
        let start = peer_offset + 1;
        let end = start + peer_len;
        if end > raw.len() {
            bail!("invite payload truncated at peer field");
        }
        Some(String::from_utf8(raw[start..end].to_vec())
            .context("peer addr is not valid UTF-8")?)
    };

    // Extension 1: admin pubkey (u16 BE length prefix). Absent in older invites.
    let ext1_offset = peer_offset + 1 + peer_len;
    let (admin_pubkey_bytes, ext2_offset) = if ext1_offset + 2 <= raw.len() {
        let len = u16::from_be_bytes([raw[ext1_offset], raw[ext1_offset + 1]]) as usize;
        let start = ext1_offset + 2;
        let end = start + len;
        if len > 0 && end <= raw.len() {
            (Some(raw[start..end].to_vec()), end)
        } else {
            (None, start)
        }
    } else {
        (None, ext1_offset)
    };

    // Extension 2: relay addr (u16 BE length prefix). Absent in older invites.
    let (relay_addr, ext3_offset) = if ext2_offset + 2 <= raw.len() {
        let len = u16::from_be_bytes([raw[ext2_offset], raw[ext2_offset + 1]]) as usize;
        let start = ext2_offset + 2;
        let end = start + len;
        if len > 0 && end <= raw.len() {
            (Some(String::from_utf8(raw[start..end].to_vec())
                .context("relay addr is not valid UTF-8")?), end)
        } else {
            (None, start)
        }
    } else {
        (None, ext2_offset)
    };

    // Extension 3: rendezvous addr (u16 BE length prefix). Absent in older invites.
    let rendezvous_addr = if ext3_offset + 2 <= raw.len() {
        let len = u16::from_be_bytes([raw[ext3_offset], raw[ext3_offset + 1]]) as usize;
        let start = ext3_offset + 2;
        let end = start + len;
        if len > 0 && end <= raw.len() {
            Some(String::from_utf8(raw[start..end].to_vec())
                .context("rendezvous addr is not valid UTF-8")?)
        } else {
            None
        }
    } else {
        None
    };

    Ok(InvitePayload { circle_id, psk_bytes, circle_name, expires_at, peer_addr, admin_pubkey_bytes, relay_addr, rendezvous_addr })
}

// ── Expiry ────────────────────────────────────────────────────────────────────

pub fn check_expiry(payload: &InvitePayload) -> Result<()> {
    let now = Utc::now();
    if now > payload.expires_at {
        let ago = now - payload.expires_at;
        bail!(
            "invite expired {} ago (at {})",
            format_duration(ago),
            payload.expires_at.format("%Y-%m-%d %H:%M UTC")
        );
    }
    Ok(())
}

// ── TTL parsing ───────────────────────────────────────────────────────────────

pub fn parse_ttl(s: &str) -> Result<Duration> {
    if let Some(days) = s.strip_suffix('d') {
        let n: i64 = days.parse().context("invalid number of days in TTL")?;
        Ok(Duration::days(n))
    } else if let Some(hours) = s.strip_suffix('h') {
        let n: i64 = hours.parse().context("invalid number of hours in TTL")?;
        Ok(Duration::hours(n))
    } else {
        bail!("invalid TTL '{}' — use e.g. '7d' or '24h'", s)
    }
}

// ── Helpers ───────────────────────────────────────────────────────────────────

fn format_duration(d: Duration) -> String {
    let secs = d.num_seconds().abs();
    if secs < 60 {
        format!("{secs}s")
    } else if secs < 3600 {
        format!("{}m", secs / 60)
    } else if secs < 86400 {
        format!("{}h", secs / 3600)
    } else {
        format!("{}d", secs / 86400)
    }
}

// ── Tests ─────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn round_trip_basic() {
        let psk = [42u8; 32];
        let expires = Utc::now() + Duration::days(7);
        let payload = InvitePayload {
            circle_id:   "8e563c41-f0ec-4225-9764-064f1fb04341".to_string(),
            psk_bytes:   psk,
            circle_name: Some("TestCircle".to_string()),
            expires_at:  expires,
            peer_addr:   Some("/ip4/1.2.3.4/tcp/9091".to_string()),
            admin_pubkey_bytes: None,
            relay_addr:  Some("/ip4/5.6.7.8/tcp/36521/p2p/12D3KooWtest".to_string()),
            rendezvous_addr: Some("/ip4/9.10.11.12/udp/36521/quic-v1/p2p/12D3KooWrdvz".to_string()),
        };

        let uri = encode(&payload);
        assert!(uri.starts_with("enoxian://v1/"));
        assert!(!uri.contains('?'), "URI must not have a query string");
        assert!(!uri.contains('&'), "URI must not contain & (shell unsafe)");

        let decoded = decode(&uri).unwrap();
        assert_eq!(decoded.circle_id, payload.circle_id);
        assert_eq!(decoded.psk_bytes, psk);
        assert_eq!(decoded.circle_name.as_deref(), Some("TestCircle"));
        assert_eq!(decoded.peer_addr.as_deref(), Some("/ip4/1.2.3.4/tcp/9091"));
        assert_eq!(decoded.relay_addr.as_deref(), Some("/ip4/5.6.7.8/tcp/36521/p2p/12D3KooWtest"));
        assert_eq!(decoded.rendezvous_addr.as_deref(), Some("/ip4/9.10.11.12/udp/36521/quic-v1/p2p/12D3KooWrdvz"));
        // expires_at loses sub-second precision (stored as i64 unix seconds)
        assert_eq!(decoded.expires_at.timestamp(), expires.timestamp());
    }

    #[test]
    fn round_trip_no_name_no_peer() {
        let psk = [0u8; 32];
        let expires = Utc::now() + Duration::hours(24);
        let payload = InvitePayload {
            circle_id:   "8e563c41-f0ec-4225-9764-064f1fb04341".to_string(),
            psk_bytes:   psk,
            circle_name: None,
            expires_at:  expires,
            peer_addr:   None,
            admin_pubkey_bytes: None,
            relay_addr:  None,
            rendezvous_addr: None,
        };
        let uri = encode(&payload);
        let decoded = decode(&uri).unwrap();
        assert!(decoded.circle_name.is_none());
        assert!(decoded.peer_addr.is_none());
    }

    #[test]
    fn expiry_detected() {
        let psk = [0u8; 32];
        let payload = InvitePayload {
            circle_id:   "8e563c41-f0ec-4225-9764-064f1fb04341".to_string(),
            psk_bytes:   psk,
            circle_name: None,
            expires_at:  Utc::now() - Duration::hours(1),
            peer_addr:   None,
            admin_pubkey_bytes: None,
            relay_addr:  None,
            rendezvous_addr: None,
        };
        let uri = encode(&payload);
        let decoded = decode(&uri).unwrap();
        assert!(check_expiry(&decoded).is_err());
    }

    #[test]
    fn ttl_parsing() {
        assert_eq!(parse_ttl("7d").unwrap(), Duration::days(7));
        assert_eq!(parse_ttl("24h").unwrap(), Duration::hours(24));
        assert!(parse_ttl("bad").is_err());
    }
}
