//! `enoxian://` invite URI encoding, decoding, and expiry validation.
//!
//! Two wire versions exist. v2 is what we mint; v1 is still decoded so links
//! already in circulation keep working.
//!
//! # v2
//!
//! A leading flags byte says which optional fields follow, so an absent field
//! costs nothing rather than a zero length prefix, and every field is carried
//! in its most compact form: multiaddrs in libp2p's binary encoding rather than
//! as text, the grant as raw key/nonce/signature bytes rather than hex, the
//! expiry as a `u32`. Measured against the same fully loaded invite, v2 is 515
//! characters where v1 was 843; the common invite, whose relay and rendezvous
//! are the compiled-in defaults, is 372. Most of what v1 spent was text
//! encoding of data that is natively binary.
//!
//! ```text
//!   byte   0      flags (see the FLAG_* constants)
//!   bytes  1-16   circle UUID
//!   bytes 17-48   PSK (32 raw bytes)
//!   bytes 49-52   expires_at as u32 Unix timestamp (big-endian)
//!   then, in order, only those fields the flags mark present:
//!     circle name     u8 length + UTF-8
//!     peer addr       address field (see `put_addr`)
//!     admin pubkey    u8 length + raw bytes
//!     relay addr      address field   — only when FLAG_RELAY_ADDR
//!     rendezvous addr address field   — only when FLAG_RENDEZVOUS_ADDR
//!     grant           u8 length + inviter pubkey, tagged nonce, u8 length + sig
//! ```
//!
//! The relay and rendezvous servers each have a second flag meaning "the
//! compiled-in default". Both point at the same host for a stock build, so the
//! common invite would otherwise spend ~190 bytes spelling out an address the
//! reader's own binary already knows. The joiner resolves the default the same
//! way the daemon does at startup; only a self-hosted server pays for the bytes.
//!
//! # v1
//!
//! ```text
//!   bytes  0-15   circle UUID (big-endian)
//!   bytes 16-47   PSK (32 raw bytes)
//!   bytes 48-55   expires_at as i64 Unix timestamp (big-endian)
//!   byte  56      name length N (u8)
//!   bytes 57..    circle_name (UTF-8, N bytes)
//!   byte  57+N    peer length M (u8)
//!   bytes 58+N..  peer_addr (UTF-8, M bytes)
//!   then u16-length-prefixed extensions: admin pubkey, relay addr,
//!   rendezvous addr, and the grant as three UTF-8 fields.
//! ```
//!
//! Full URI (no query string — safe to paste in any shell without quoting):
//!   enoxian://v2/<base64url-no-pad>

use anyhow::{bail, Context, Result};
use base64::{engine::general_purpose::URL_SAFE_NO_PAD, Engine};
use chacha20poly1305::aead::{Aead, Payload};
use chacha20poly1305::{ChaCha20Poly1305, Key, KeyInit, Nonce};
use chrono::{DateTime, Duration, Utc};
use hkdf::Hkdf;
use libp2p::Multiaddr;
use rand::TryRng;
use sha2::Sha256;
use uuid::Uuid;

const SCHEME_V1: &str = "enoxian://v1/";
const SCHEME_V2: &str = "enoxian://v2/";
const MIN_LEN_V1: usize = 58; // 16 + 32 + 8 + 1 + 1
const MIN_LEN_V2: usize = 53; // 1 + 16 + 32 + 4

// ── v2 flags ──────────────────────────────────────────────────────────────────

const FLAG_NAME: u8 = 0x01;
const FLAG_PEER: u8 = 0x02;
const FLAG_ADMIN: u8 = 0x04;
/// An explicit relay multiaddr follows.
const FLAG_RELAY_ADDR: u8 = 0x08;
/// The relay is `defaults::DEFAULT_RELAY`; no address is carried.
const FLAG_RELAY_DEFAULT: u8 = 0x10;
/// An explicit rendezvous multiaddr follows.
const FLAG_RENDEZVOUS_ADDR: u8 = 0x20;
/// The rendezvous server is `defaults::DEFAULT_RENDEZVOUS`; no address is carried.
const FLAG_RENDEZVOUS_DEFAULT: u8 = 0x40;
const FLAG_GRANT: u8 = 0x80;

/// Tag on an address field: libp2p's binary multiaddr encoding.
const ADDR_BINARY: u8 = 0;
/// Tag on an address field: UTF-8 text, for anything that would not parse.
const ADDR_TEXT: u8 = 1;

/// The latest expiry a v2 invite can carry, from the `u32` timestamp: 2106-02-07.
///
/// `parse_ttl` refuses anything beyond it, so the limit is reported as a bad
/// argument rather than surfacing much later from `encode`.
fn max_expiry() -> DateTime<Utc> {
    DateTime::from_timestamp(i64::from(u32::MAX), 0).expect("u32::MAX is a valid Unix timestamp")
}

/// Tag on a grant nonce: 16 raw UUID bytes.
const NONCE_UUID: u8 = 0;
/// Tag on a grant nonce: UTF-8 text, for a nonce that is not a UUID.
const NONCE_TEXT: u8 = 1;

pub struct InvitePayload {
    pub circle_id: String,
    pub psk_bytes: [u8; 32],
    pub circle_name: Option<String>,
    pub expires_at: DateTime<Utc>,
    pub peer_addr: Option<String>,
    /// Admin public key (protobuf-encoded bytes). Present when generated by the circle admin.
    pub admin_pubkey_bytes: Option<Vec<u8>>,
    /// Circuit relay multiaddr (e.g. /ip4/1.2.3.4/tcp/36521/p2p/<peer_id>).
    /// Joinees add this to their relay_addrs and use it for WAN connectivity.
    pub relay_addr: Option<String>,
    /// Rendezvous server multiaddr (QUIC, e.g. /ip4/1.2.3.4/udp/36521/quic-v1/p2p/<peer_id>).
    /// Joinees add this to their rendezvous_addrs for automatic peer discovery.
    pub rendezvous_addr: Option<String>,
    /// The relay is the compiled-in default, carried as a flag instead of an
    /// address. `relay_addr` is `None` and the joiner resolves
    /// [`crate::defaults::DEFAULT_RELAY`] itself — see [`resolve_defaults`].
    ///
    /// Never set at the same time as `relay_addr`; a v1 invite decodes with it
    /// false, because v1 had no way to say this.
    pub relay_is_default: bool,
    /// As `relay_is_default`, for [`crate::defaults::DEFAULT_RENDEZVOUS`].
    pub rendezvous_is_default: bool,
    /// The grant: who issued this invite, a one-time nonce, and their signature.
    ///
    /// Present on invites minted by a member; absent on invites predating the
    /// grant. Without it an invite is only a bearer credential — anyone holding
    /// the circle's PSK can mint one, set any expiry they like, and no later
    /// change to the circle can invalidate it. The grant binds the invite to a
    /// member whose standing is re-checked when it is redeemed.
    pub grant: Option<InviteGrant>,
}

/// Issuer, nonce and signature carried by an invite.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct InviteGrant {
    /// hex(protobuf) of the issuing member's per-circle public key.
    ///
    /// The key rather than the peer ID: the peer ID is derived from it, so this
    /// both identifies the issuer and verifies the signature without a lookup.
    pub inviter_pubkey_hex: String,
    /// One-time identifier, recorded when redeemed so an invite admits once.
    pub nonce: String,
    /// hex(sign(inviter_circle_key, [`grant_message`]))
    pub sig: String,
}

impl InviteGrant {
    /// Peer ID of the issuer, derived from the carried key.
    pub fn inviter_peer_id(&self) -> Result<String> {
        Ok(self.inviter_public_key()?.to_peer_id().to_string())
    }

    fn inviter_public_key(&self) -> Result<libp2p::identity::PublicKey> {
        let bytes = hex::decode(self.inviter_pubkey_hex.trim())
            .context("inviter public key is not valid hex")?;
        libp2p::identity::PublicKey::try_decode_protobuf(&bytes)
            .map_err(|e| anyhow::anyhow!("invalid inviter public key: {e}"))
    }
}

/// Mint a grant for an invite, signing with this member's per-circle key.
///
/// Every member holds such a key, so issuing invites stays open to the whole
/// circle — the grant records *which* member issued it, not that an admin did.
pub fn sign_grant(
    circle_id: &str,
    keypair_proto_hex: &str,
    expires_at: DateTime<Utc>,
) -> Result<InviteGrant> {
    let keypair = crate::crypto::keypair_from_hex(keypair_proto_hex)?;
    let nonce = Uuid::new_v4().to_string();
    let sig = keypair
        .sign(&grant_message(circle_id, &nonce, expires_at))
        .map_err(|e| anyhow::anyhow!("signing invite grant failed: {e}"))?;
    Ok(InviteGrant {
        inviter_pubkey_hex: hex::encode(keypair.public().encode_protobuf()),
        nonce,
        sig: hex::encode(sig),
    })
}

/// Check that a grant was signed by the key it names, over this circle, nonce
/// and expiry.
///
/// This proves only authorship. Whether the issuer is *still* entitled to admit
/// anyone is a separate question, answered against live membership at the point
/// the invite is redeemed — that separation is what lets removing a member
/// invalidate the invites they issued.
pub fn verify_grant(circle_id: &str, grant: &InviteGrant, expires_at: DateTime<Utc>) -> Result<()> {
    let pubkey = grant.inviter_public_key()?;
    let sig = hex::decode(grant.sig.trim()).context("grant signature is not valid hex")?;
    if !pubkey.verify(&grant_message(circle_id, &grant.nonce, expires_at), &sig) {
        bail!("invite grant signature does not match the issuing key");
    }
    Ok(())
}

/// Canonical bytes an inviter signs. Covers the circle, the nonce and the
/// expiry, so none of the three can be altered without invalidating the grant —
/// which is what makes a TTL mean anything.
pub fn grant_message(circle_id: &str, nonce: &str, expires_at: DateTime<Utc>) -> Vec<u8> {
    format!("invite:{circle_id}:{nonce}:{}", expires_at.timestamp()).into_bytes()
}

// ── Short invites ─────────────────────────────────────────────────────────────

/// Prefix of a short invite — one that keeps its contents on a relay.
pub const SCHEME_SHORT: &str = "enoxian://s1/";

/// Bytes of key material in a short invite.
///
/// 128 bits, and it is the whole secret: it names the blob and unseals it. A
/// short link is pasted, not retyped, so there is no reason to shave this the
/// way a pairing code is shaved — and unlike a pairing code, nothing else
/// stands behind it. Anyone holding the link holds the invite, exactly as with
/// a long one.
const SHORT_KEY_BYTES: usize = 16;

const INFO_BLOB_ID: &[u8] = b"enoxian-invite-blob/id";
const INFO_BLOB_KEY: &[u8] = b"enoxian-invite-blob/key";

/// The key a short invite carries, and the two values derived from it.
#[derive(Clone)]
pub struct ShortKey([u8; SHORT_KEY_BYTES]);

/// Redacted: this is the whole invite. It should be rendered by `link`, and
/// nowhere else.
impl std::fmt::Debug for ShortKey {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("ShortKey(redacted)")
    }
}

impl ShortKey {
    pub fn generate() -> Result<Self> {
        let mut bytes = [0u8; SHORT_KEY_BYTES];
        rand::rngs::SysRng
            .try_fill_bytes(&mut bytes)
            .map_err(|e| anyhow::anyhow!("reading OS entropy for an invite key failed: {e}"))?;
        Ok(ShortKey(bytes))
    }

    fn derive(&self, info: &[u8]) -> [u8; 32] {
        let mut out = [0u8; 32];
        Hkdf::<Sha256>::new(None, &self.0)
            .expand(info, &mut out)
            .expect("HKDF output length is within bounds");
        out
    }

    /// Where the sealed payload sits. Derived rather than carried, so the
    /// server is told an id that reveals nothing about the key behind it.
    pub fn blob_id(&self) -> String {
        hex::encode(self.derive(INFO_BLOB_ID))
    }

    fn seal_key(&self) -> [u8; 32] {
        self.derive(INFO_BLOB_KEY)
    }

    /// Seal an encoded invite for the relay to hold.
    pub fn seal(&self, invite_bytes: &[u8]) -> Result<Vec<u8>> {
        let mut nonce = [0u8; 12];
        rand::rngs::SysRng
            .try_fill_bytes(&mut nonce)
            .map_err(|e| anyhow::anyhow!("reading OS entropy for an invite nonce failed: {e}"))?;

        let cipher = ChaCha20Poly1305::new(&Key::from(self.seal_key()));
        let ciphertext = cipher
            .encrypt(
                &Nonce::from(nonce),
                Payload {
                    msg: invite_bytes,
                    // The id is bound in, so a blob cannot be moved to another.
                    aad: self.blob_id().as_bytes(),
                },
            )
            .map_err(|_| anyhow::anyhow!("sealing the invite failed"))?;

        let mut out = Vec::with_capacity(12 + ciphertext.len());
        out.extend_from_slice(&nonce);
        out.extend_from_slice(&ciphertext);
        Ok(out)
    }

    /// Open what the relay handed back.
    pub fn open(&self, sealed: &[u8]) -> Result<Vec<u8>> {
        if sealed.len() < 12 + 16 {
            bail!("the invite this link points at is too short to be valid");
        }
        let (nonce_bytes, ciphertext) = sealed.split_at(12);
        let nonce: [u8; 12] = nonce_bytes
            .try_into()
            .expect("split_at(12) yields 12 bytes");
        ChaCha20Poly1305::new(&Key::from(self.seal_key()))
            .decrypt(
                &Nonce::from(nonce),
                Payload {
                    msg: ciphertext,
                    aad: self.blob_id().as_bytes(),
                },
            )
            .map_err(|_| {
                anyhow::anyhow!("this invite link did not open — it may have been altered")
            })
    }
}

/// A short invite: the key, and where to fetch from when that is not the
/// build's own relay.
pub struct ShortInvite {
    pub key: ShortKey,
    /// `None` means the compiled-in default. A self-hosted relay is named, at
    /// the cost of a longer link — still far shorter than carrying the payload.
    pub host: Option<String>,
}

impl ShortInvite {
    /// `enoxian://s1/<key>` — plus `@host` when it is not the default relay.
    pub fn encode(&self) -> String {
        let key = URL_SAFE_NO_PAD.encode(self.key.0);
        match self.host {
            Some(ref host) => format!("{SCHEME_SHORT}{key}@{host}"),
            None => format!("{SCHEME_SHORT}{key}"),
        }
    }

    pub fn decode(uri: &str) -> Result<Self> {
        let body = uri
            .trim()
            .strip_prefix(SCHEME_SHORT)
            .with_context(|| format!("not a short enoxian:// invite: {uri}"))?;

        let (key_part, host) = match body.split_once('@') {
            Some((k, h)) if !h.is_empty() => (k, Some(h.to_string())),
            _ => (body, None),
        };

        let bytes = URL_SAFE_NO_PAD
            .decode(key_part)
            .context("invite key is not valid base64url")?;
        let bytes: [u8; SHORT_KEY_BYTES] = bytes
            .try_into()
            .map_err(|_| anyhow::anyhow!("invite key is the wrong length"))?;

        Ok(ShortInvite {
            key: ShortKey(bytes),
            host,
        })
    }
}

/// Whether this looks like a short invite rather than a self-contained one.
pub fn is_short(uri: &str) -> bool {
    uri.trim().starts_with(SCHEME_SHORT)
}

// ── Encoding ──────────────────────────────────────────────────────────────────

/// Append a length as an unsigned LEB128 varint.
///
/// One byte for anything under 128, which in practice is every field here — a
/// circle name, a binary multiaddr, a key, a signature — so the common invite
/// pays exactly what a `u8` prefix would have cost. A field that runs longer
/// spills into a second byte instead of being refused: a multiaddr built on a
/// long DNS name can exceed 255 bytes, and v1 encoded those fine.
fn put_len(out: &mut Vec<u8>, mut n: usize) {
    loop {
        let byte = (n & 0x7f) as u8;
        n >>= 7;
        if n == 0 {
            out.push(byte);
            return;
        }
        out.push(byte | 0x80);
    }
}

/// Append a length-prefixed run of bytes.
fn put_bytes(out: &mut Vec<u8>, bytes: &[u8]) {
    put_len(out, bytes.len());
    out.extend_from_slice(bytes);
}

/// Append an address as a tag byte plus a length-prefixed run.
///
/// libp2p's binary encoding is roughly half the size of the text form — an
/// `/ip4/…/tcp/…/p2p/…` address is ~47 bytes against ~84 — because the peer ID
/// is carried as the multihash it already is rather than re-spelled in base58.
/// Anything that will not parse is kept verbatim as text, so a hand-written
/// `--peer` value survives the round trip either way.
fn put_addr(out: &mut Vec<u8>, addr: &str) {
    match addr.parse::<Multiaddr>() {
        Ok(m) => {
            out.push(ADDR_BINARY);
            put_bytes(out, &m.to_vec());
        }
        Err(_) => {
            out.push(ADDR_TEXT);
            put_bytes(out, addr.as_bytes());
        }
    }
}

/// Encode an invite as an `enoxian://v2/` URI.
///
/// Fallible rather than panicking: an expiry beyond [`MAX_EXPIRY`] or a grant
/// whose fields are not hex cannot be represented, and a caller that has
/// already written state to disk needs to report that, not abort. `parse_ttl`
/// rejects an out-of-range expiry earlier still, before any of that state
/// exists.
pub fn encode(payload: &InvitePayload) -> Result<String> {
    let uuid = Uuid::parse_str(&payload.circle_id).context("circle_id must be a valid UUID")?;

    let ts = payload.expires_at.timestamp();
    let ts = u32::try_from(ts).map_err(|_| {
        anyhow::anyhow!(
            "an invite cannot expire at {} — the latest it can carry is {}",
            payload.expires_at.format("%Y-%m-%d %H:%M UTC"),
            max_expiry().format("%Y-%m-%d %H:%M UTC")
        )
    })?;

    let mut flags = 0u8;
    if payload.circle_name.is_some() {
        flags |= FLAG_NAME;
    }
    if payload.peer_addr.is_some() {
        flags |= FLAG_PEER;
    }
    if payload.admin_pubkey_bytes.is_some() {
        flags |= FLAG_ADMIN;
    }
    // An explicit address wins over the default flag: the two are mutually
    // exclusive on the wire, and carrying the address is never wrong.
    if payload.relay_addr.is_some() {
        flags |= FLAG_RELAY_ADDR;
    } else if payload.relay_is_default {
        flags |= FLAG_RELAY_DEFAULT;
    }
    if payload.rendezvous_addr.is_some() {
        flags |= FLAG_RENDEZVOUS_ADDR;
    } else if payload.rendezvous_is_default {
        flags |= FLAG_RENDEZVOUS_DEFAULT;
    }
    if payload.grant.is_some() {
        flags |= FLAG_GRANT;
    }

    let mut raw = Vec::with_capacity(MIN_LEN_V2 + 128);
    raw.push(flags);
    raw.extend_from_slice(uuid.as_bytes());
    raw.extend_from_slice(&payload.psk_bytes);
    raw.extend_from_slice(&ts.to_be_bytes());

    if let Some(ref name) = payload.circle_name {
        put_bytes(&mut raw, name.as_bytes());
    }
    if let Some(ref peer) = payload.peer_addr {
        put_addr(&mut raw, peer);
    }
    if let Some(ref admin) = payload.admin_pubkey_bytes {
        put_bytes(&mut raw, admin);
    }
    if let Some(ref relay) = payload.relay_addr {
        put_addr(&mut raw, relay);
    }
    if let Some(ref rendezvous) = payload.rendezvous_addr {
        put_addr(&mut raw, rendezvous);
    }
    if let Some(ref grant) = payload.grant {
        // Both key and signature are hex on the struct because that is what
        // callers and the control doc use; on the wire they are the bytes that
        // hex was spelling, which halves them.
        let inviter = hex::decode(grant.inviter_pubkey_hex.trim())
            .context("grant inviter pubkey is not valid hex")?;
        put_bytes(&mut raw, &inviter);

        match Uuid::parse_str(&grant.nonce) {
            Ok(id) => {
                raw.push(NONCE_UUID);
                raw.extend_from_slice(id.as_bytes());
            }
            Err(_) => {
                raw.push(NONCE_TEXT);
                put_bytes(&mut raw, grant.nonce.as_bytes());
            }
        }

        let sig = hex::decode(grant.sig.trim()).context("grant signature is not valid hex")?;
        put_bytes(&mut raw, &sig);
    }

    Ok(format!("{SCHEME_V2}{}", URL_SAFE_NO_PAD.encode(&raw)))
}

// ── Decoding ──────────────────────────────────────────────────────────────────

/// Cursor over a v2 payload. Every read is bounds-checked and names the field
/// it was reading, so a truncated invite says where it ran out.
struct Reader<'a> {
    raw: &'a [u8],
    at: usize,
}

impl<'a> Reader<'a> {
    fn take(&mut self, n: usize, what: &str) -> Result<&'a [u8]> {
        let end = self
            .at
            .checked_add(n)
            .context("invite payload length overflowed")?;
        if end > self.raw.len() {
            bail!("invite payload truncated at {what}");
        }
        let out = &self.raw[self.at..end];
        self.at = end;
        Ok(out)
    }

    fn byte(&mut self, what: &str) -> Result<u8> {
        Ok(self.take(1, what)?[0])
    }

    /// An unsigned LEB128 length, as written by `put_len`.
    fn len(&mut self, what: &str) -> Result<usize> {
        let mut n: usize = 0;
        let mut shift = 0u32;
        loop {
            // Five groups of seven bits cover any length a 16 MB-capped URI
            // could hold. More than that is a malformed or hostile payload
            // rather than a long field, and must not be allowed to spin.
            if shift > 28 {
                bail!("length prefix for {what} is malformed");
            }
            let byte = self.byte(what)?;
            n |= ((byte & 0x7f) as usize) << shift;
            if byte & 0x80 == 0 {
                return Ok(n);
            }
            shift += 7;
        }
    }

    /// A length-prefixed run.
    fn bytes(&mut self, what: &str) -> Result<&'a [u8]> {
        let len = self.len(what)?;
        self.take(len, what)
    }

    fn text(&mut self, what: &str) -> Result<String> {
        let bytes = self.bytes(what)?;
        String::from_utf8(bytes.to_vec()).with_context(|| format!("{what} is not valid UTF-8"))
    }

    fn addr(&mut self, what: &str) -> Result<String> {
        match self.byte(what)? {
            ADDR_BINARY => {
                let bytes = self.bytes(what)?;
                Ok(Multiaddr::try_from(bytes.to_vec())
                    .with_context(|| format!("{what} is not a valid multiaddr"))?
                    .to_string())
            }
            ADDR_TEXT => self.text(what),
            other => bail!("unknown address encoding {other} for {what}"),
        }
    }
}

pub fn decode(uri: &str) -> Result<InvitePayload> {
    // Strip any query string that old clients might have produced
    let uri_clean = uri.split_once('?').map(|(base, _)| base).unwrap_or(uri);

    if let Some(b64) = uri_clean.strip_prefix(SCHEME_V2) {
        return decode_v2(b64);
    }
    if let Some(b64) = uri_clean.strip_prefix(SCHEME_V1) {
        return decode_v1(b64);
    }
    bail!("not a valid enoxian:// URI: {uri}")
}

fn decode_v2(b64: &str) -> Result<InvitePayload> {
    let raw = URL_SAFE_NO_PAD
        .decode(b64)
        .context("invite URI payload is not valid base64url")?;

    if raw.len() < MIN_LEN_V2 {
        bail!(
            "invite payload is {} bytes, expected at least {MIN_LEN_V2}",
            raw.len()
        );
    }

    let mut r = Reader { raw: &raw, at: 0 };
    let flags = r.byte("flags")?;

    let uuid_bytes: [u8; 16] = r.take(16, "circle id")?.try_into().unwrap();
    let circle_id = Uuid::from_bytes(uuid_bytes).to_string();
    let psk_bytes: [u8; 32] = r.take(32, "psk")?.try_into().unwrap();
    let ts = u32::from_be_bytes(r.take(4, "expiry")?.try_into().unwrap());
    let expires_at =
        DateTime::from_timestamp(i64::from(ts), 0).context("invalid timestamp in invite")?;

    let circle_name = if flags & FLAG_NAME != 0 {
        Some(r.text("circle name")?)
    } else {
        None
    };
    let peer_addr = if flags & FLAG_PEER != 0 {
        Some(r.addr("peer addr")?)
    } else {
        None
    };
    let admin_pubkey_bytes = if flags & FLAG_ADMIN != 0 {
        Some(r.bytes("admin pubkey")?.to_vec())
    } else {
        None
    };
    let relay_addr = if flags & FLAG_RELAY_ADDR != 0 {
        Some(r.addr("relay addr")?)
    } else {
        None
    };
    let rendezvous_addr = if flags & FLAG_RENDEZVOUS_ADDR != 0 {
        Some(r.addr("rendezvous addr")?)
    } else {
        None
    };

    let grant = if flags & FLAG_GRANT != 0 {
        let inviter_pubkey_hex = hex::encode(r.bytes("inviter pubkey")?);
        let nonce = match r.byte("grant nonce")? {
            NONCE_UUID => {
                let bytes: [u8; 16] = r.take(16, "grant nonce")?.try_into().unwrap();
                Uuid::from_bytes(bytes).to_string()
            }
            NONCE_TEXT => r.text("grant nonce")?,
            other => bail!("unknown nonce encoding {other}"),
        };
        let sig = hex::encode(r.bytes("grant signature")?);
        // A grant with an empty field would verify against nothing; treat it as
        // no grant at all rather than a partial one downstream might wave
        // through. Same rule as v1.
        if inviter_pubkey_hex.is_empty() || nonce.is_empty() || sig.is_empty() {
            None
        } else {
            Some(InviteGrant {
                inviter_pubkey_hex,
                nonce,
                sig,
            })
        }
    } else {
        None
    };

    Ok(InvitePayload {
        circle_id,
        psk_bytes,
        circle_name,
        expires_at,
        peer_addr,
        admin_pubkey_bytes,
        relay_addr,
        // A default flag only means anything when no address was carried; the
        // encoder never sets both, and a reader that saw both should trust the
        // address it actually has.
        relay_is_default: relay_addr_is_default(flags),
        rendezvous_addr,
        rendezvous_is_default: rendezvous_addr_is_default(flags),
        grant,
    })
}

fn relay_addr_is_default(flags: u8) -> bool {
    flags & FLAG_RELAY_DEFAULT != 0 && flags & FLAG_RELAY_ADDR == 0
}

fn rendezvous_addr_is_default(flags: u8) -> bool {
    flags & FLAG_RENDEZVOUS_DEFAULT != 0 && flags & FLAG_RENDEZVOUS_ADDR == 0
}

/// Resolve the compiled-in default relay and rendezvous addresses for an invite
/// that asked for them by flag.
///
/// Kept out of [`decode`] because decoding is pure and this reaches the network:
/// the default is a hostname, and turning it into a multiaddr means asking the
/// bootstrap server for its peer ID — exactly what the daemon does at startup.
/// A server that cannot be reached leaves the field `None`, the same
/// non-fatal outcome as an invite that carried no address at all.
pub async fn resolve_defaults(payload: &mut InvitePayload) {
    use crate::commands::rendezvous as rdvz;

    if payload.relay_is_default && payload.relay_addr.is_none() {
        payload.relay_addr = rdvz::resolve_default_relay().await;
    }
    if payload.rendezvous_is_default && payload.rendezvous_addr.is_none() {
        payload.rendezvous_addr = rdvz::resolve_default().await;
    }
}

fn decode_v1(b64: &str) -> Result<InvitePayload> {
    let raw = URL_SAFE_NO_PAD
        .decode(b64)
        .context("invite URI payload is not valid base64url")?;

    if raw.len() < MIN_LEN_V1 {
        bail!(
            "invite payload is {} bytes, expected at least {MIN_LEN_V1}",
            raw.len()
        );
    }

    let uuid_bytes: [u8; 16] = raw[..16].try_into().unwrap();
    let circle_id = Uuid::from_bytes(uuid_bytes).to_string();

    let psk_bytes: [u8; 32] = raw[16..48].try_into().unwrap();

    let ts = i64::from_be_bytes(raw[48..56].try_into().unwrap());
    let expires_at = DateTime::from_timestamp(ts, 0).context("invalid timestamp in invite")?;

    let name_len = raw[56] as usize;
    if 57 + name_len >= raw.len() {
        bail!("invite payload truncated at name field");
    }
    let circle_name = if name_len == 0 {
        None
    } else {
        Some(
            String::from_utf8(raw[57..57 + name_len].to_vec())
                .context("circle name is not valid UTF-8")?,
        )
    };

    let peer_offset = 57 + name_len;
    let peer_len = raw[peer_offset] as usize;
    let peer_addr = if peer_len == 0 {
        None
    } else {
        let start = peer_offset + 1;
        let end = start + peer_len;
        if end > raw.len() {
            bail!("invite payload truncated at peer field");
        }
        Some(String::from_utf8(raw[start..end].to_vec()).context("peer addr is not valid UTF-8")?)
    };

    // Extension 1: admin pubkey (u16 BE length prefix). Absent in older invites.
    let ext1_offset = peer_offset + 1 + peer_len;
    let (admin_pubkey_bytes, ext2_offset) = if ext1_offset + 2 <= raw.len() {
        let len = u16::from_be_bytes([raw[ext1_offset], raw[ext1_offset + 1]]) as usize;
        let start = ext1_offset + 2;
        let end = start + len;
        if len > 0 && end <= raw.len() {
            (Some(raw[start..end].to_vec()), end)
        } else {
            (None, start)
        }
    } else {
        (None, ext1_offset)
    };

    // Extension 2: relay addr (u16 BE length prefix). Absent in older invites.
    let (relay_addr, ext3_offset) = if ext2_offset + 2 <= raw.len() {
        let len = u16::from_be_bytes([raw[ext2_offset], raw[ext2_offset + 1]]) as usize;
        let start = ext2_offset + 2;
        let end = start + len;
        if len > 0 && end <= raw.len() {
            (
                Some(
                    String::from_utf8(raw[start..end].to_vec())
                        .context("relay addr is not valid UTF-8")?,
                ),
                end,
            )
        } else {
            (None, start)
        }
    } else {
        (None, ext2_offset)
    };

    // Extension 3: rendezvous addr (u16 BE length prefix). Absent in older invites.
    let mut ext4_offset = ext3_offset;
    let rendezvous_addr = if ext3_offset + 2 <= raw.len() {
        let len = u16::from_be_bytes([raw[ext3_offset], raw[ext3_offset + 1]]) as usize;
        let start = ext3_offset + 2;
        let end = start + len;
        if len > 0 && end <= raw.len() {
            ext4_offset = end;
            Some(
                String::from_utf8(raw[start..end].to_vec())
                    .context("rendezvous addr is not valid UTF-8")?,
            )
        } else {
            ext4_offset = start;
            None
        }
    } else {
        None
    };

    // Extension 4: the grant. All three fields must be present and non-empty
    // for the invite to carry one; anything else decodes as no grant at all,
    // never as a partial one that might be waved through downstream.
    let mut grant_fields: Vec<String> = Vec::with_capacity(3);
    let mut offset = ext4_offset;
    for _ in 0..3 {
        if offset + 2 > raw.len() {
            break;
        }
        let len = u16::from_be_bytes([raw[offset], raw[offset + 1]]) as usize;
        let start = offset + 2;
        let end = start + len;
        if end > raw.len() {
            break;
        }
        grant_fields.push(
            String::from_utf8(raw[start..end].to_vec())
                .context("grant field is not valid UTF-8")?,
        );
        offset = end;
    }
    let grant = match grant_fields.as_slice() {
        [inviter, nonce, sig] if !inviter.is_empty() && !nonce.is_empty() && !sig.is_empty() => {
            Some(InviteGrant {
                inviter_pubkey_hex: inviter.clone(),
                nonce: nonce.clone(),
                sig: sig.clone(),
            })
        }
        _ => None,
    };

    Ok(InvitePayload {
        circle_id,
        psk_bytes,
        circle_name,
        expires_at,
        peer_addr,
        admin_pubkey_bytes,
        relay_addr,
        rendezvous_addr,
        // v1 had no way to say "the default"; an address was carried or it was not.
        relay_is_default: false,
        rendezvous_is_default: false,
        grant,
    })
}

// ── Expiry ────────────────────────────────────────────────────────────────────

pub fn check_expiry(payload: &InvitePayload) -> Result<()> {
    let now = Utc::now();
    if now > payload.expires_at {
        let ago = now - payload.expires_at;
        bail!(
            "invite expired {} ago (at {})",
            format_duration(ago),
            payload.expires_at.format("%Y-%m-%d %H:%M UTC")
        );
    }
    Ok(())
}

// ── TTL parsing ───────────────────────────────────────────────────────────────

pub fn parse_ttl(s: &str) -> Result<Duration> {
    let ttl = if let Some(days) = s.strip_suffix('d') {
        let n: i64 = days.parse().context("invalid number of days in TTL")?;
        Duration::try_days(n).with_context(|| format!("TTL '{s}' is out of range"))?
    } else if let Some(hours) = s.strip_suffix('h') {
        let n: i64 = hours.parse().context("invalid number of hours in TTL")?;
        Duration::try_hours(n).with_context(|| format!("TTL '{s}' is out of range"))?
    } else {
        bail!("invalid TTL '{s}' — use e.g. '7d' or '24h'")
    };

    // The range check belongs here, not in `encode`. A TTL is a command-line
    // argument, and callers parse it before they start writing: `enox init`
    // saves the circle config, the admin key and the MLS group before it mints
    // the first invite, so an expiry rejected at encode time would leave a
    // half-made circle behind a failed command.
    let expires_at = Utc::now()
        .checked_add_signed(ttl)
        .with_context(|| format!("TTL '{s}' is out of range"))?;
    if u32::try_from(expires_at.timestamp()).is_err() {
        bail!(
            "TTL '{s}' expires at {}, later than an invite can express — \
             the limit is {}",
            expires_at.format("%Y-%m-%d"),
            max_expiry().format("%Y-%m-%d")
        );
    }
    Ok(ttl)
}

// ── Helpers ───────────────────────────────────────────────────────────────────

fn format_duration(d: Duration) -> String {
    let secs = d.num_seconds().abs();
    if secs < 60 {
        format!("{secs}s")
    } else if secs < 3600 {
        format!("{}m", secs / 60)
    } else if secs < 86400 {
        format!("{}h", secs / 3600)
    } else {
        format!("{}d", secs / 86400)
    }
}

// ── Tests ─────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn round_trip_basic() {
        let psk = [42u8; 32];
        let expires = Utc::now() + Duration::days(7);
        let payload = InvitePayload {
            grant: None,
            circle_id: "8e563c41-f0ec-4225-9764-064f1fb04341".to_string(),
            psk_bytes: psk,
            circle_name: Some("TestCircle".to_string()),
            expires_at: expires,
            peer_addr: Some("/ip4/1.2.3.4/tcp/9091".to_string()),
            admin_pubkey_bytes: None,
            relay_addr: Some("/ip4/5.6.7.8/tcp/36521/p2p/12D3KooWtest".to_string()),
            rendezvous_addr: Some("/ip4/9.10.11.12/udp/36521/quic-v1/p2p/12D3KooWrdvz".to_string()),
            relay_is_default: false,
            rendezvous_is_default: false,
        };

        let uri = encode(&payload).unwrap();
        assert!(uri.starts_with("enoxian://v2/"));
        assert!(!uri.contains('?'), "URI must not have a query string");
        assert!(!uri.contains('&'), "URI must not contain & (shell unsafe)");

        let decoded = decode(&uri).unwrap();
        assert_eq!(decoded.circle_id, payload.circle_id);
        assert_eq!(decoded.psk_bytes, psk);
        assert_eq!(decoded.circle_name.as_deref(), Some("TestCircle"));
        assert_eq!(decoded.peer_addr.as_deref(), Some("/ip4/1.2.3.4/tcp/9091"));
        assert_eq!(
            decoded.relay_addr.as_deref(),
            Some("/ip4/5.6.7.8/tcp/36521/p2p/12D3KooWtest")
        );
        assert_eq!(
            decoded.rendezvous_addr.as_deref(),
            Some("/ip4/9.10.11.12/udp/36521/quic-v1/p2p/12D3KooWrdvz")
        );
        // expires_at loses sub-second precision (stored as i64 unix seconds)
        assert_eq!(decoded.expires_at.timestamp(), expires.timestamp());
    }

    #[test]
    fn round_trip_no_name_no_peer() {
        let psk = [0u8; 32];
        let expires = Utc::now() + Duration::hours(24);
        let payload = InvitePayload {
            grant: None,
            circle_id: "8e563c41-f0ec-4225-9764-064f1fb04341".to_string(),
            psk_bytes: psk,
            circle_name: None,
            expires_at: expires,
            peer_addr: None,
            admin_pubkey_bytes: None,
            relay_addr: None,
            rendezvous_addr: None,
            relay_is_default: false,
            rendezvous_is_default: false,
        };
        let uri = encode(&payload).unwrap();
        let decoded = decode(&uri).unwrap();
        assert!(decoded.circle_name.is_none());
        assert!(decoded.peer_addr.is_none());
    }

    #[test]
    fn expiry_detected() {
        let psk = [0u8; 32];
        let payload = InvitePayload {
            grant: None,
            circle_id: "8e563c41-f0ec-4225-9764-064f1fb04341".to_string(),
            psk_bytes: psk,
            circle_name: None,
            expires_at: Utc::now() - Duration::hours(1),
            peer_addr: None,
            admin_pubkey_bytes: None,
            relay_addr: None,
            rendezvous_addr: None,
            relay_is_default: false,
            rendezvous_is_default: false,
        };
        let uri = encode(&payload).unwrap();
        let decoded = decode(&uri).unwrap();
        assert!(check_expiry(&decoded).is_err());
    }

    /// Build a v1 invite the way the old encoder did, so the compatibility
    /// tests below exercise the real historical bytes rather than a
    /// reconstruction that happens to agree with today's decoder.
    fn encode_v1(payload: &InvitePayload) -> String {
        let uuid = Uuid::parse_str(&payload.circle_id).unwrap();
        let name_bytes = payload.circle_name.as_deref().unwrap_or("").as_bytes();
        let peer_bytes = payload.peer_addr.as_deref().unwrap_or("").as_bytes();
        let admin_bytes = payload.admin_pubkey_bytes.as_deref().unwrap_or(&[]);
        let relay_bytes = payload.relay_addr.as_deref().unwrap_or("").as_bytes();
        let rendezvous_bytes = payload.rendezvous_addr.as_deref().unwrap_or("").as_bytes();

        let mut raw = Vec::new();
        raw.extend_from_slice(uuid.as_bytes());
        raw.extend_from_slice(&payload.psk_bytes);
        raw.extend_from_slice(&payload.expires_at.timestamp().to_be_bytes());
        raw.push(name_bytes.len() as u8);
        raw.extend_from_slice(name_bytes);
        raw.push(peer_bytes.len() as u8);
        raw.extend_from_slice(peer_bytes);
        for ext in [admin_bytes, relay_bytes, rendezvous_bytes] {
            raw.extend_from_slice(&(ext.len() as u16).to_be_bytes());
            raw.extend_from_slice(ext);
        }
        let (inviter, nonce, sig) = match &payload.grant {
            Some(g) => (
                g.inviter_pubkey_hex.as_str(),
                g.nonce.as_str(),
                g.sig.as_str(),
            ),
            None => ("", "", ""),
        };
        for field in [inviter, nonce, sig] {
            raw.extend_from_slice(&(field.len() as u16).to_be_bytes());
            raw.extend_from_slice(field.as_bytes());
        }
        format!("{SCHEME_V1}{}", URL_SAFE_NO_PAD.encode(&raw))
    }

    fn realistic(grant: Option<InviteGrant>) -> InvitePayload {
        InvitePayload {
            circle_id: "8e563c41-f0ec-4225-9764-064f1fb04341".to_string(),
            psk_bytes: [42u8; 32],
            circle_name: Some("acme-eng".to_string()),
            expires_at: DateTime::from_timestamp(1_800_000_000, 0).unwrap(),
            peer_addr: Some(
                "/ip4/192.168.1.42/tcp/36521/p2p/\
                 12D3KooWGjMkHkMvzGrzGHkPmuvFmbrzBXV9NwYWnYVvbcJRHMo3"
                    .to_string(),
            ),
            admin_pubkey_bytes: Some(vec![9u8; 36]),
            relay_addr: Some(
                "/ip4/203.0.113.17/tcp/36522/p2p/\
                 12D3KooWQbnLYdEz6f2EfSQXHkZbmWCTyPWk8WjbNmaTnDqDCeYk/p2p-circuit"
                    .to_string(),
            ),
            rendezvous_addr: Some(
                "/ip4/203.0.113.17/udp/36521/quic-v1/p2p/\
                 12D3KooWQbnLYdEz6f2EfSQXHkZbmWCTyPWk8WjbNmaTnDqDCeYk"
                    .to_string(),
            ),
            relay_is_default: false,
            rendezvous_is_default: false,
            grant,
        }
    }

    fn a_grant() -> InviteGrant {
        InviteGrant {
            inviter_pubkey_hex: hex::encode([3u8; 36]),
            nonce: Uuid::new_v4().to_string(),
            sig: hex::encode([7u8; 64]),
        }
    }

    /// The point of v2. A fully loaded invite — every optional field present,
    /// nothing elided — must come out substantially shorter than the same one in
    /// v1. The bound is deliberately a little loose: what matters is that the
    /// compaction holds, not the exact byte count, which moves with the length
    /// of a circle name or a multiaddr.
    ///
    /// At the time of writing this pair measures 515 against 843.
    #[test]
    fn a_v2_invite_is_far_shorter_than_the_v1_it_replaces() {
        let payload = realistic(Some(a_grant()));
        let v1 = encode_v1(&payload);
        let v2 = encode(&payload).unwrap();

        assert!(
            v2.len() * 3 < v1.len() * 2,
            "v2 is {} chars, v1 is {} — expected under two thirds",
            v2.len(),
            v1.len()
        );
        assert!(v2.len() < 560, "v2 invite grew to {} chars", v2.len());
    }

    /// Eliding the two default servers is the rest of the saving, and it is the
    /// common case: a stock build points relay and rendezvous at the same host.
    #[test]
    fn naming_the_default_servers_costs_nothing() {
        let mut payload = realistic(Some(a_grant()));
        let with_addrs = encode(&payload).unwrap();

        payload.relay_addr = None;
        payload.rendezvous_addr = None;
        payload.relay_is_default = true;
        payload.rendezvous_is_default = true;
        let with_flags = encode(&payload).unwrap();

        // 515 -> 372 at the time of writing. This is the shape of invite the
        // CLI actually mints on a stock build, so it is the number that matters.
        assert!(
            with_addrs.len() - with_flags.len() > 100,
            "eliding both defaults saved only {} chars",
            with_addrs.len() - with_flags.len()
        );
        assert!(
            with_flags.len() < 400,
            "the common invite grew to {} chars",
            with_flags.len()
        );

        let decoded = decode(&with_flags).unwrap();
        assert!(decoded.relay_is_default);
        assert!(decoded.rendezvous_is_default);
        assert!(decoded.relay_addr.is_none());
        assert!(decoded.rendezvous_addr.is_none());
    }

    /// An address that was carried explicitly is used as-is — the default flag
    /// must not be inferred from its absence, or a self-hosted relay would
    /// silently become the public one.
    #[test]
    fn an_explicit_address_is_never_reported_as_the_default() {
        let decoded = decode(&encode(&realistic(None)).unwrap()).unwrap();
        assert!(!decoded.relay_is_default);
        assert!(!decoded.rendezvous_is_default);
        assert_eq!(decoded.relay_addr, realistic(None).relay_addr);
        assert_eq!(decoded.rendezvous_addr, realistic(None).rendezvous_addr);
    }

    /// Multiaddrs travel in libp2p's binary form, which is where most of the
    /// saving comes from, and must come back spelled exactly as they went in.
    #[test]
    fn multiaddrs_survive_the_binary_encoding() {
        let payload = realistic(None);
        let decoded = decode(&encode(&payload).unwrap()).unwrap();
        assert_eq!(decoded.peer_addr, payload.peer_addr);
        assert_eq!(decoded.relay_addr, payload.relay_addr);
        assert_eq!(decoded.rendezvous_addr, payload.rendezvous_addr);
    }

    /// An address that is not a multiaddr at all — a hand-typed `--peer`, say —
    /// falls back to text rather than being rejected or mangled.
    #[test]
    fn an_unparseable_address_falls_back_to_text() {
        let mut payload = realistic(None);
        payload.peer_addr = Some("not-a-multiaddr-at-all".to_string());
        let decoded = decode(&encode(&payload).unwrap()).unwrap();
        assert_eq!(decoded.peer_addr.as_deref(), Some("not-a-multiaddr-at-all"));
    }

    /// Links already in circulation keep working, including the grant they
    /// carry — a v1 invite in someone's chat history must still admit them.
    #[test]
    fn a_v1_invite_still_decodes() {
        let payload = realistic(Some(a_grant()));
        let decoded = decode(&encode_v1(&payload)).unwrap();

        assert_eq!(decoded.circle_id, payload.circle_id);
        assert_eq!(decoded.psk_bytes, payload.psk_bytes);
        assert_eq!(decoded.circle_name, payload.circle_name);
        assert_eq!(decoded.peer_addr, payload.peer_addr);
        assert_eq!(decoded.relay_addr, payload.relay_addr);
        assert_eq!(decoded.rendezvous_addr, payload.rendezvous_addr);
        assert_eq!(decoded.admin_pubkey_bytes, payload.admin_pubkey_bytes);
        assert_eq!(decoded.grant, payload.grant);
        assert_eq!(
            decoded.expires_at.timestamp(),
            payload.expires_at.timestamp()
        );
        // v1 could not express this, so it must never come back true.
        assert!(!decoded.relay_is_default);
        assert!(!decoded.rendezvous_is_default);
    }

    /// The grant's signature covers a decimal expiry and a string nonce, so the
    /// compacted `u32` timestamp and 16-byte nonce have to render back to
    /// exactly the text that was signed or every v2 invite would fail to verify.
    #[test]
    fn a_grant_still_verifies_after_the_compaction() {
        use crate::crypto::keypair_to_hex;
        use libp2p::identity::Keypair;

        let kp = Keypair::generate_ed25519();
        let circle = "8e563c41-f0ec-4225-9764-064f1fb04341";
        let expires = DateTime::from_timestamp(1_800_000_000, 0).unwrap();
        let grant = sign_grant(circle, &keypair_to_hex(&kp).unwrap(), expires).unwrap();

        let mut payload = realistic(Some(grant));
        payload.circle_id = circle.to_string();
        payload.expires_at = expires;

        let decoded = decode(&encode(&payload).unwrap()).unwrap();
        let back = decoded.grant.expect("grant survives v2 encoding");
        assert!(verify_grant(circle, &back, decoded.expires_at).is_ok());
    }

    /// A nonce that is not a UUID is not something `sign_grant` produces, but a
    /// grant that came from elsewhere must not be silently corrupted into one.
    #[test]
    fn a_non_uuid_nonce_round_trips_as_text() {
        let mut payload = realistic(Some(a_grant()));
        payload.grant.as_mut().unwrap().nonce = "legacy-nonce-value".to_string();
        let decoded = decode(&encode(&payload).unwrap()).unwrap();
        assert_eq!(decoded.grant.unwrap().nonce, "legacy-nonce-value");
    }

    /// A payload cut short must say so rather than decoding into a half-filled
    /// invite — the flags promise fields that a truncated link cannot deliver.
    #[test]
    fn a_truncated_v2_payload_is_rejected() {
        let uri = encode(&realistic(Some(a_grant()))).unwrap();
        let b64 = uri.strip_prefix(SCHEME_V2).unwrap();
        let raw = URL_SAFE_NO_PAD.decode(b64).unwrap();

        for cut in [MIN_LEN_V2 + 1, raw.len() - 20, raw.len() - 1] {
            let truncated = format!("{SCHEME_V2}{}", URL_SAFE_NO_PAD.encode(&raw[..cut]));
            assert!(
                decode(&truncated).is_err(),
                "a payload cut to {cut} bytes decoded anyway"
            );
        }
    }

    /// A multiaddr built on a long DNS name runs past 255 bytes. v1 carried
    /// those, so v2 must too — the varint length prefix spills into a second
    /// byte rather than refusing the address.
    #[test]
    fn a_relay_address_longer_than_255_bytes_still_encodes() {
        let host = "a".repeat(223);
        let relay = format!(
            "/dns4/{host}/tcp/36522/p2p/\
             12D3KooWQbnLYdEz6f2EfSQXHkZbmWCTyPWk8WjbNmaTnDqDCeYk"
        );
        assert!(
            relay.parse::<Multiaddr>().unwrap().to_vec().len() > 255,
            "test needs an address whose binary form exceeds a u8 length"
        );

        let mut payload = realistic(Some(a_grant()));
        payload.relay_addr = Some(relay.clone());

        let decoded = decode(&encode(&payload).unwrap()).unwrap();
        assert_eq!(decoded.relay_addr.as_deref(), Some(relay.as_str()));
    }

    /// The varint is one byte below 128 and two at 128, so the common invite
    /// pays exactly what a `u8` prefix would have. Both sides of that boundary
    /// have to round-trip.
    #[test]
    fn fields_either_side_of_the_varint_boundary_round_trip() {
        for len in [127usize, 128, 129] {
            let mut payload = realistic(None);
            payload.circle_name = Some("n".repeat(len));
            let decoded = decode(&encode(&payload).unwrap()).unwrap();
            assert_eq!(
                decoded.circle_name.as_deref().map(str::len),
                Some(len),
                "a {len}-byte name did not survive"
            );
        }
    }

    /// A `u32` expiry cannot reach the year 36 500 days out. That has to be
    /// refused while it is still a command-line argument: `enox init` writes
    /// the circle config, the admin key and the MLS group before it mints an
    /// invite, so failing at encode time would leave a half-made circle.
    #[test]
    fn a_ttl_beyond_the_expressible_range_is_rejected_at_parse_time() {
        let err = parse_ttl("36500d").expect_err("a 100-year TTL cannot be carried");
        let msg = err.to_string();
        assert!(
            msg.contains("36500d") && msg.contains("limit"),
            "the error should name the TTL and the limit, got: {msg}"
        );

        // The TTLs people actually use stay accepted.
        assert!(parse_ttl("7d").is_ok());
        assert!(parse_ttl("365d").is_ok());
    }

    /// Whatever `parse_ttl` accepts, `encode` must be able to carry — otherwise
    /// the check in front of the side effects is not the check that matters.
    #[test]
    fn every_accepted_ttl_can_be_encoded() {
        for ttl in ["1h", "24h", "7d", "365d", "3650d"] {
            let mut payload = realistic(None);
            payload.expires_at = Utc::now() + parse_ttl(ttl).unwrap();
            assert!(
                encode(&payload).is_ok(),
                "parse_ttl accepted {ttl} but encode refused it"
            );
        }
    }

    /// An expiry built without going through `parse_ttl` still cannot panic —
    /// it comes back as an ordinary error naming the limit.
    #[test]
    fn an_unencodable_expiry_is_an_error_not_a_panic() {
        let mut payload = realistic(None);
        payload.expires_at = DateTime::from_timestamp(i64::from(u32::MAX) + 1, 0).unwrap();
        let err = encode(&payload).expect_err("an expiry past 2106 cannot be carried");
        assert!(err.to_string().contains("2106"), "got: {err}");
    }

    /// Malformed hex in a grant is likewise an error rather than a panic; the
    /// struct carries hex because callers do, so it can hold anything.
    #[test]
    fn a_malformed_grant_is_an_error_not_a_panic() {
        let mut payload = realistic(Some(a_grant()));
        payload.grant.as_mut().unwrap().sig = "not hex".to_string();
        assert!(encode(&payload).is_err());
    }

    /// A length prefix that never terminates must be rejected rather than read
    /// forever.
    #[test]
    fn a_runaway_length_prefix_is_rejected() {
        let mut raw = vec![FLAG_NAME];
        raw.extend_from_slice(&[0u8; 16]); // circle id
        raw.extend_from_slice(&[0u8; 32]); // psk
        raw.extend_from_slice(&0u32.to_be_bytes()); // expiry
        raw.extend_from_slice(&[0xff; 16]); // a length prefix with no final byte
        let uri = format!("{SCHEME_V2}{}", URL_SAFE_NO_PAD.encode(&raw));
        assert!(decode(&uri).is_err());
    }

    #[test]
    fn an_unknown_scheme_version_is_rejected() {
        assert!(decode("enoxian://v9/AAAA").is_err());
        assert!(decode("https://example.com/AAAA").is_err());
    }

    // ── Short invites ────────────────────────────────────────────────────────

    /// The point: a link short enough to paste anywhere. The long form of the
    /// same invite is ~300 characters.
    #[test]
    fn a_short_invite_is_a_fraction_of_the_long_one() {
        let long = encode(&realistic(Some(a_grant()))).unwrap();
        let short = ShortInvite {
            key: ShortKey::generate().unwrap(),
            host: None,
        }
        .encode();

        assert_eq!(short.len(), 35, "got {short}");
        assert!(
            short.len() * 8 < long.len(),
            "short {} vs long {}",
            short.len(),
            long.len()
        );
    }

    #[test]
    fn a_short_invite_round_trips() {
        let key = ShortKey::generate().unwrap();
        let id = key.blob_id();
        let uri = ShortInvite { key, host: None }.encode();

        let back = ShortInvite::decode(&uri).unwrap();
        assert_eq!(back.key.blob_id(), id);
        assert!(back.host.is_none());
        assert!(is_short(&uri));
        assert!(!is_short(&encode(&realistic(None)).unwrap()));
    }

    /// A self-hosted relay is named in the link, at the cost of some length.
    #[test]
    fn a_named_relay_survives_the_round_trip() {
        let uri = ShortInvite {
            key: ShortKey::generate().unwrap(),
            host: Some("pair.example.com".into()),
        }
        .encode();

        let back = ShortInvite::decode(&uri).unwrap();
        assert_eq!(back.host.as_deref(), Some("pair.example.com"));
    }

    /// The whole invite travels sealed; the relay holds bytes it cannot read.
    #[test]
    fn the_payload_seals_and_opens() {
        let long = encode(&realistic(Some(a_grant()))).unwrap();
        let key = ShortKey::generate().unwrap();

        let sealed = key.seal(long.as_bytes()).unwrap();
        assert!(
            !String::from_utf8_lossy(&sealed).contains("enoxian://"),
            "the relay must not be handed anything legible"
        );
        assert_eq!(String::from_utf8(key.open(&sealed).unwrap()).unwrap(), long);
    }

    /// Another key must not open it, and tampering must fail the tag rather
    /// than yield rubbish that later parses as something.
    #[test]
    fn a_sealed_invite_resists_the_wrong_key_and_tampering() {
        let long = encode(&realistic(None)).unwrap();
        let key = ShortKey::generate().unwrap();
        let sealed = key.seal(long.as_bytes()).unwrap();

        assert!(ShortKey::generate().unwrap().open(&sealed).is_err());
        for i in [0usize, 12, sealed.len() - 1] {
            let mut bad = sealed.clone();
            bad[i] ^= 0x01;
            assert!(key.open(&bad).is_err(), "byte {i} went unnoticed");
        }
        assert!(key.open(&sealed[..8]).is_err());
    }

    /// The id is what the relay is told. It must not be the key, nor let the
    /// key be worked back out, nor be the value that unseals the blob.
    #[test]
    fn the_blob_id_reveals_nothing() {
        let key = ShortKey::generate().unwrap();
        let id = key.blob_id();
        assert_eq!(id.len(), 64);
        assert!(id.bytes().all(|b| b.is_ascii_hexdigit()));

        let uri = ShortInvite {
            key: key.clone(),
            host: None,
        }
        .encode();
        let encoded_key = uri.strip_prefix(SCHEME_SHORT).unwrap();
        assert!(!id.contains(encoded_key));

        // Distinct keys reach distinct blobs.
        let mut seen = std::collections::HashSet::new();
        for _ in 0..200 {
            assert!(seen.insert(ShortKey::generate().unwrap().blob_id()));
        }
    }

    #[test]
    fn a_malformed_short_invite_is_refused() {
        assert!(ShortInvite::decode("enoxian://s1/").is_err());
        assert!(ShortInvite::decode("enoxian://s1/not-base64!!").is_err());
        assert!(
            ShortInvite::decode("enoxian://s1/AAAA").is_err(),
            "too short"
        );
        assert!(
            ShortInvite::decode("enoxian://v2/AAAA").is_err(),
            "wrong scheme"
        );
    }

    /// A short link must never be mistaken for a self-contained one, or
    /// `decode` would try to read a key as a payload.
    #[test]
    fn a_short_invite_is_not_decoded_as_a_long_one() {
        let uri = ShortInvite {
            key: ShortKey::generate().unwrap(),
            host: None,
        }
        .encode();
        assert!(decode(&uri).is_err());
    }

    #[test]
    fn ttl_parsing() {
        assert_eq!(parse_ttl("7d").unwrap(), Duration::days(7));
        assert_eq!(parse_ttl("24h").unwrap(), Duration::hours(24));
        assert!(parse_ttl("bad").is_err());
    }
}

#[cfg(test)]
mod grant_tests {
    use super::*;
    use crate::crypto::keypair_to_hex;
    use libp2p::identity::Keypair;

    fn member() -> (String, String) {
        let kp = Keypair::generate_ed25519();
        (
            keypair_to_hex(&kp).unwrap(),
            kp.public().to_peer_id().to_string(),
        )
    }

    #[test]
    fn a_grant_verifies_and_names_its_issuer() {
        let (hex, peer) = member();
        let exp = Utc::now() + Duration::days(1);
        let grant = sign_grant("circle-1", &hex, exp).unwrap();
        assert!(verify_grant("circle-1", &grant, exp).is_ok());
        assert_eq!(grant.inviter_peer_id().unwrap(), peer);
    }

    /// The signature covers circle, nonce and expiry, so none can be edited
    /// after the fact. Extending the expiry is the interesting one: without it
    /// covered, a TTL would be a suggestion rather than a limit.
    #[test]
    fn none_of_the_signed_fields_can_be_altered() {
        let (hex, _) = member();
        let exp = Utc::now() + Duration::days(1);
        let grant = sign_grant("circle-1", &hex, exp).unwrap();

        assert!(verify_grant("circle-2", &grant, exp).is_err(), "circle");
        assert!(
            verify_grant("circle-1", &grant, exp + Duration::days(365)).is_err(),
            "expiry"
        );
        let mut tampered = grant.clone();
        tampered.nonce = "different".into();
        assert!(verify_grant("circle-1", &tampered, exp).is_err(), "nonce");
    }

    /// A grant cannot be re-attributed to someone else: swapping in another
    /// member's key breaks the signature, so an invite can never appear to
    /// have been issued by a member who did not issue it.
    #[test]
    fn a_grant_cannot_be_reattributed_to_another_member() {
        let (issuer_hex, _) = member();
        let (_, other_peer) = member();
        let (other_hex, _) = member();
        let exp = Utc::now() + Duration::days(1);

        let mut grant = sign_grant("circle-1", &issuer_hex, exp).unwrap();
        let other_pub = crate::crypto::keypair_from_hex(&other_hex)
            .unwrap()
            .public()
            .encode_protobuf();
        grant.inviter_pubkey_hex = hex::encode(other_pub);

        assert!(verify_grant("circle-1", &grant, exp).is_err());
        assert_ne!(grant.inviter_peer_id().unwrap(), other_peer);
    }

    #[test]
    fn a_grant_survives_the_invite_encoding() {
        let (hex, peer) = member();
        let exp = Utc::now() + Duration::days(1);
        let grant = sign_grant("00000000-0000-0000-0000-000000000001", &hex, exp).unwrap();
        let uri = encode(&InvitePayload {
            circle_id: "00000000-0000-0000-0000-000000000001".into(),
            psk_bytes: [7u8; 32],
            circle_name: Some("c".into()),
            expires_at: exp,
            peer_addr: None,
            admin_pubkey_bytes: None,
            relay_addr: None,
            rendezvous_addr: None,
            relay_is_default: false,
            rendezvous_is_default: false,
            grant: Some(grant),
        })
        .unwrap();
        let back = decode(&uri)
            .unwrap()
            .grant
            .expect("grant survives encoding");
        assert_eq!(back.inviter_peer_id().unwrap(), peer);
        assert!(verify_grant("00000000-0000-0000-0000-000000000001", &back, exp).is_ok());
    }

    /// Invites minted before grants existed must still decode — as carrying no
    /// grant, never as a partial one that downstream might treat as present.
    #[test]
    fn an_invite_without_a_grant_decodes_as_none() {
        let uri = encode(&InvitePayload {
            circle_id: "00000000-0000-0000-0000-000000000002".into(),
            psk_bytes: [1u8; 32],
            circle_name: None,
            expires_at: Utc::now() + Duration::days(1),
            peer_addr: None,
            admin_pubkey_bytes: None,
            relay_addr: None,
            rendezvous_addr: None,
            relay_is_default: false,
            rendezvous_is_default: false,
            grant: None,
        })
        .unwrap();
        assert!(decode(&uri).unwrap().grant.is_none());
    }
}
